package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestGenerateWheelBytes(t *testing.T) {
	size := 300
	stride := size * 4 // ARGB32, 4-byte aligned already
	buf := generateWheelBytes(size, stride)
	if len(buf) != stride*size {
		t.Fatalf("buffer length = %d want %d", len(buf), stride*size)
	}

	// Center pixel: sat ~= 0 -> white (all channels high, alpha 255).
	c := (size/2)*stride + (size/2)*4
	if buf[c+3] != 255 {
		t.Errorf("center alpha = %d want 255", buf[c+3])
	}
	if buf[c] < 250 || buf[c+1] < 250 || buf[c+2] < 250 {
		t.Errorf("center should be near white, got B=%d G=%d R=%d", buf[c], buf[c+1], buf[c+2])
	}

	// A pixel on the right edge (max saturation, hue 0 -> red).
	edge := (size/2)*stride + (size-1)*4
	if buf[edge+3] != 255 {
		t.Errorf("edge alpha = %d want 255 (should be inside circle)", buf[edge+3])
	}
	if buf[edge+2] < 200 { // R channel
		t.Errorf("right edge should be saturated red, R=%d", buf[edge+2])
	}

	// A corner pixel is outside the circle -> untouched (alpha 0).
	corner := 0
	if buf[corner+3] != 0 {
		t.Errorf("corner alpha = %d want 0 (outside circle)", buf[corner+3])
	}
}

func TestWheelCacheRoundTrip(t *testing.T) {
	dir := t.TempDir()
	cache := filepath.Join(dir, ".wheel_cache.bin")
	size, stride := 64, 64*4

	first := wheelBytes(cache, size, stride)
	if _, err := os.Stat(cache); err != nil {
		t.Fatalf("cache not written: %v", err)
	}
	second := wheelBytes(cache, size, stride)
	if string(first) != string(second) {
		t.Errorf("cached bytes differ from generated bytes")
	}
	if len(second) != stride*size {
		t.Errorf("cached buffer length = %d want %d", len(second), stride*size)
	}
}
